name: playground

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating system to run'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - ubuntu-latest
        - windows-latest
      run_cmd:
        description: 'Command to execute'
        required: true 
        type: string
      run_shell:
        description: 'run shell'
        required: true 
        type: choice
        default: 'bash'
        options:
        - bash
        # - python
        # - sh
        # - cmd
        # - pwsh
        # - powershell

jobs:
  execute-your-task:
    runs-on: ${{ github.event.inputs.os }} 
    steps:
      - name: Show the command
        shell: bash
        run: |
          echo shell: $run_shell
          echo command: $run_cmd
        env:
          run_shell: ${{ github.event.inputs.run_shell }}
          run_cmd: ${{ github.event.inputs.run_cmd }}
      - name: Run the command
        # shell: ${{ github.event.inputs.run_shell }}
        shell: bash
        run: ${{ github.event.inputs.run_cmd }} 
